# Update docs/vh.html when this value changes, and follow the instructions there, under the "Version Update" heading.
PV=1.2.9

# Dependencies, also update shoring/pom.xml
FXV=22-ea+16
GSONV=2.10.1
HTTPV=5.3
KV=1.9.10
