set JAVA_HOME=%USERPROFILE%\apps\jdk
set MAVEN_HOME=%USERPROFILE%\apps\mvn
set GRADLE_HOME=%USERPROFILE%\apps\gradle
set ANT_HOME=%USERPROFILE%\apps\ant
set PATH=%JAVA_HOME%\bin;%MAVEN_HOME%\bin;%GRADLE_HOME%\bin;%ANT_HOME%\bin;%PATH%
